require 'rake/testtask'


Rake::TestTask.new do |t|
  t.libs << 'tests'
  t.test_files = FileList['tests/test*.rb']
  t.verbose = true
end


task :default => [:run]


task :run do
  # ruby './bin/temp_class.rb'
  ruby './bin/main_class.rb'
  # ruby './lib/base_highlighter.rb'
  # ruby './lib/html_ruby_util.rb'
  # ruby './lib/html_builder.rb'
  # ruby './lib/html_util.rb'
end
