require 'rake/testtask'

Rake::TestTask.new do |t|
  t.libs << "tests"
  t.test_files = FileList['tests/test*.rb']
  t.verbose = true
end

task :default => [:run]

task :run do
  ruby "./lib/anki_source_to_tsv.rb"
end