require 'rake/testtask'

Rake::TestTask.new do |t|
  t.libs << "tests"
  t.test_files = FileList['tests/test*.rb']
  t.verbose = true
end

task :default => [:run]


task :run do
  ruby './bin/klass/inheritance2.rb'
end

